# raise ValueError

try:
    raise KeyError
except KeyError :
    print ('Я сгенерировал ошибку!')